services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${SERVICE_PORT}:8000
    volumes:
      - .:/app
      - ./persistent_data:/app/persistent_data
      - ./temp_chunks:/app/temp_chunks
    environment:
      - PYTHONPATH=/app